# Travis yaml grantmacken/alpine-openresty
# https://github.com/grantmacken/alpine-openresty
sudo: required
dist: trusty
os: linux
language: c
services:
  - docker
env:
  global:
    - DOCKER_IMAGE="grantmacken/alpine-openresty"
jobs:
   include:
    - stage: build base docker image
      install: skip
      script:
      - echo '${DOCKER_USERNAME}'
      - mkdir -p tmp
      - make tmp/openresty-latest.version
      - export DOCKER_TAG=$(cat tmp/openresty-latest.version | grep -oE '([0-9]+\.[0-9]+\.[0-9]+\.[0-9]+)')
      - echo -n 'DOCKER IMAGE: '
      - echo "${DOCKER_IMAGE}"
      - echo -n 'DOCKER TAG: '
      - echo "${DOCKER_TAG}"
      - docker build --tag ${DOCKER_IMAGE}:base-v${DOCKER_TAG} .  >/dev/null 2>&1
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker push ${DOCKER_IMAGE}:base-v${DOCKER_TAG}
    - stage: build base docker image
      install: skip
      script:
      - mkdir -p tmp
      - make tmp/openresty-latest.version
      - export DOCKER_TAG=$(cat tmp/openresty-latest.version | grep -oE '([0-9]+\.[0-9]+\.[0-9]+\.[0-9]+)')
      - echo "${DOCKER_TAG}"

