# Travis yaml grantmacken/alpine-openresty
# https://github.com/grantmacken/alpine-openresty
sudo: required
dist: xenial
os: linux
language: minimal
services:
  - docker
install: make build
script:
  - docker-compose up -d
  - docker ps
  - docker exec or ls . | grep 'nginx'
  - docker exec or which resty | grep 'resty'
  - docker exec or which opm | grep 'opm'
  - docker exec or which openresty | grep 'openresty'
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
# - docker push "grantmacken/alpine-openresty:${DOCKER_TAG}"


