# Travis yaml grantmacken/alpine-openresty
# https://github.com/grantmacken/alpine-openresty
sudo: required
dist: trusty
os: linux
language: c
services:
  - docker
env:
  global:
    - DOCKER_IMAGE="grantmacken/alpine-openresty"
    - MAKEFLAGS="-j 4"
# before_- MAKEFLAGS="-j 2"script:
#   - docker pull "$IMAGE" || true
# script:
#   - docker build --pull --cache-from "$IMAGE" --tag "$IMAGE" .
#   - docker run -d $IMAGE
# after_script:
#   - docker images
#   - docker ps
#   - docker run --entrypoint "" $IMAGE ls -al .
#   - docker run --entrypoint "" $IMAGE ./bin/openresty -V
#   - docker-compose version

jobs:
   include:
    - stage: download versioning
      before_install:
      - pwd
      - which make
      - which cat
      - mkdir tmp
      script:
        - make tmp/openresty-latest.version
        - cat  tmp/openresty-latest.version | grep -oE '([0-9]+\.[0-9]+\.[0-9]+\.[0-9]+)'
        - export DOCKER_TAG=$(cat tmp/openresty-latest.version | grep -oE '([0-9]+\.[0-9]+\.[0-9]+\.[0-9]+)')
    - stage: install from sources
      script:
        - export DOCKER_TAG=$(cat tmp/openresty-latest.version | grep -oE '([0-9]+\.[0-9]+\.[0-9]+\.[0-9]+)')
        - echo "${DOCKER_TAG}"
        - docker build --tag ${DOCKER_IMAGE}:${DOCKER_TAG} .
