# Travis yaml grantmacken/alpine-openresty
# https://github.com/grantmacken/alpine-openresty
sudo: required
dist: trusty
os: linux
language: c
services:
  - docker

jobs:
   include:
    - stage: base
      if: branch = master
      install: skip
      script:
      - mkdir -p tmp
      - make tmp/openresty-latest.version
      - export DOCKER_TAG=$(cat tmp/openresty-latest.version | grep -oE '([0-9]+\.[0-9]+\.[0-9]+\.[0-9]+)')
      - echo "${DOCKER_TAG}"
      - docker build --tag  "grantmacken/alpine-exist:base-v${DOCKER_TAG}" .
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker push "grantmacken/alpine-exist:base-v${DOCKER_TAG}"


