# Travis yaml grantmacken/alpine-openresty
# https://github.com/grantmacken/alpine-openresty
sudo: required
dist: trusty
os: linux
language: c
services:
  - docker
env:
  global:
    - DOCKER_IMAGE="grantmacken/alpine-openresty"
    - MAKEFLAGS="-j 2"
# before_- MAKEFLAGS="-j 2"script:
#   - docker pull "$IMAGE" || true
# script:
#   - docker build --pull --cache-from "$IMAGE" --tag "$IMAGE" .
#   - docker run -d $IMAGE
# after_script:
#   - docker images
#   - docker ps
#   - docker run --entrypoint "" $IMAGE ls -al .
#   - docker run --entrypoint "" $IMAGE ./bin/openresty -V
#   - docker-compose version

jobs:
   include:
    - stage: download versioning
      env:
      - DOCKER_TAG=4.3.1
      before_install:
      - pwd
      - which make
      - which cat
      script:
        - make downloads
