sudo: required
dist: trusty
os: linux
language: c
services:
  - docker
env:
  global:
    - IMAGE="grantmacken/alpine-openresty"
before_script:
  - docker pull "$IMAGE" || true
script:
  - docker run -d $IMAGE

after_script:
  - docker images
  - docker ps
