# Travis yaml grantmacken/alpine-openresty
# https://github.com/grantmacken/alpine-openresty
sudo: required
dist: trusty
os: linux
language: c
services:
  - docker
env:
  global:
    - DOCKER_IMAGE="grantmacken/alpine-openresty"
jobs:
   include:
    - stage: build base docker image
      install: skip
      script:
      - echo '${DOCKER_USERNAME}'
      - mkdir -p tmp
      - make tmp/openresty-latest.version
      - export DOCKER_TAG=$(cat tmp/openresty-latest.version | grep -oE '([0-9]+\.[0-9]+\.[0-9]+\.[0-9]+)')
      - docker build --tag ${DOCKER_IMAGE}:base-v${DOCKER_TAG} .
      - docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
    - stage: build base docker image
      install: skip
      script:
      - mkdir -p tmp
      - make tmp/openresty-latest.version
      - export DOCKER_TAG=$(cat tmp/openresty-latest.version | grep -oE '([0-9]+\.[0-9]+\.[0-9]+\.[0-9]+)')
      - echo "${DOCKER_TAG}"

