# Travis yaml grantmacken/alpine-openresty
# https://github.com/grantmacken/alpine-openresty
sudo: required
dist: trusty
os: linux
language: c
services:
  - docker
install: skip
script:
  - mkdir -p tmp
  - make tmp/openresty-latest.version
  - export DOCKER_TAG=base-v$(cat tmp/openresty-latest.version | grep -oE '([0-9]+\.[0-9]+\.[0-9]+\.[0-9]+)')
  - echo "${DOCKER_TAG}"
  - docker build --tag  "grantmacken/alpine-openresty:${DOCKER_TAG}" . >/dev/null 2>&1
  - docker-compose up -d
  - docker ps | grep ${DOCKER_TAG}
  - docker exec or ls . | grep 'nginx'
  - docker exec or which resty | grep 'resty'
  - docker exec or which openresty | grep 'openresty'

before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login -u grantmacken --password-stdin
deploy:
  provider: script
  script: docker push "grantmacken/alpine-openresty:base-v${DOCKER_TAG}"
  on:
    branch: master

#  - 
