# Travis yaml grantmacken/alpine-openresty
# https://github.com/grantmacken/alpine-openresty
sudo: required
dist: xenial
os: linux
language: c
services:
  - docker
install: skip
script:
  - mkdir -p tmp
  - export DOCKER_TAG=v$(cat .env | grep -oP '^OR_VER=\K(.+)$')
  - echo "${DOCKER_TAG}"
  - docker build --tag  "grantmacken/alpine-openresty:${DOCKER_TAG}" . >/dev/null 2>&1
  - docker-compose up -d
  - docker ps | grep ${DOCKER_TAG}
  - docker exec or ls . | grep 'nginx'
  - docker exec or which resty | grep 'resty'
  - docker exec or which openresty | grep 'openresty'
# - echo "$DOCKER_PASSWORD" | docker login -u grantmacken --password-stdin
# - docker push "grantmacken/alpine-openresty:${DOCKER_TAG}"


