# Travis yaml grantmacken/alpine-openresty
# https://github.com/grantmacken/alpine-openresty
sudo: required
dist: trusty
os: linux
language: c
services:
  - docker
env:
  global:
    - IMAGE="grantmacken/alpine-openresty"
before_script:
  - docker pull "$IMAGE" || true
script:
  - docker build --pull --cache-from "$IMAGE" --tag "$IMAGE" .
  - docker run -d $IMAGE
after_script:
  - docker images
  - docker ps
  - docker run --entrypoint "" $IMAGE ls -al .
  - docker run --entrypoint "" $IMAGE ./bin/openresty -V
  - docker-compose version
