version: '3.4'
services:
  openresty:
    build:
      context: .
      cache_from:
        - alpine:3.7
    image: grantmacken/alpine-openresty
    container_name: or
    ports:
        - 80:80
        - 443:443
    networks:
      - www
networks:
  www:
    driver: bridge

