name: alpine-openresty-ci

on:
  push:
    branches: master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      - name: make images
        run: |
          make bld
          make dev
          make min
      - name: check images
        run: |
          docker images | grep 'grantmacken'
          make run
          make stop
      - name: Push to Dockerhub and Github Packages
        run: |
          source .env
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin 
          docker push ${DOCKER_IMAGE}:dev-${OPENRESTY_VER}
          docker push ${DOCKER_IMAGE}:min-${OPENRESTY_VER}
          echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com --username ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push docker.pkg.github.com/${REPO_OWNER}/${REPO_NAME}/${PROXY_CONTAINER_NAME}:${PROXY_VER}
      # - name: build  proxy image for xqerl
      #   run: |
      #       pushd proxy/xqerl
      #       make build
      #       popd
      # - name: Push  to Github Packages
      #   run: |
      #     echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com --username ${{ secrets.DOCKER_USERNAME }} --password-stdin
      #     pushd proxy/xqerl
      #     source .env
      #     docker push docker.pkg.github.com/${REPO_OWNER}/${REPO_NAME}/${PROXY_CONTAINER_NAME}:${PROXY_VER}
      #     popd
