name: Build Then Publish Docker Images 

on:
  push:
    branches: main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: make images
        run: make
      - name: check images
        run: |
          podman image ls
          echo 'check: call resty'
          make run-resty
          echo 'check: call opm'
          make run-resty
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push to GitHub Container Registry
        run: |
          source .env
          echo "${GHPKG_REGISTRY}/${REPO_OWNER}/${REPO_NAME}:${GHPKG_VER}"
          echo "${GHPKG_REGISTRY}/${REPO_OWNER}/${REPO_NAME}:opm-${GHPKG_VER}"
          echo "${GHPKG_REGISTRY}/${REPO_OWNER}/${REPO_NAME}:resty-${GHPKG_VER}"
          podman push ${GHPKG_REGISTRY}/${REPO_OWNER}/${REPO_NAME}:${GHPKG_VER}
          podman push ${GHPKG_REGISTRY}/${REPO_OWNER}/${REPO_NAME}:resty-${GHPKG_VER}
          podman push ${GHPKG_REGISTRY}/${REPO_OWNER}/${REPO_NAME}:opm-${GHPKG_VER}

      #     make run
      #     make stop
      # - name: Push to Dockerhub and Github Packages
      #   run: |
      #     source .env
      #     echo ${{ secrets.DOCKER_PASSWORD }} | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin 
      #     docker push ${DOCKER_IMAGE}:${OPENRESTY_VER}
      #     echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com --username ${{ secrets.DOCKER_USERNAME }} --password-stdin
      #     docker push docker.pkg.github.com/${REPO_OWNER}/${REPO_NAME}/${PROXY_CONTAINER_NAME}:${PROXY_VER}
